### PR TITLE
Markdown Sublime Text 3.0 fixes

### PR DESCRIPTION
**Pull request by eyelash**
See https://github.com/sublimehq/Packages/commit/4aac501d2c6230d93fdb4916986bd97fccc51247

There are still some more things that need to be fixed, though.

### CODE REVIEW

**Comment by eyelash** [comment]
maybe going for `text.html.markdown punctuation.definition` would be preferable here?

**Comment by eyelash** [comment]
The Link & Image foreground color does not work for me (link name and URL have the same color). Don't know why, though.

**Comment by sethlopezme** [comment]
Thanks for the PR! I should be able to look it over on the 15th. I don't use Sublime Text very much anymore, but I assume this PR has to do with some changes that have popped up in the ST3 release?

**Comment by eyelash** [comment]
> Thanks for the PR! I should be able to look it over on the 15th. I don't use Sublime Text very much anymore, but I assume this PR has to do with some changes that have popped up in the ST3 release?

Yes, for the recent [3.0 release](https://www.sublimetext.com/blog/articles/sublime-text-3-point-0) the Markdown syntax highlighter changed a few scopes (for example `punctuation.definition.heading.markdown` was split into `punctuation.definition.heading.begin.markdown` and `punctuation.definition.heading.end.markdown`). I'm not really using Sublime Text either but I'm developing one of the front-ends of the [Xi editor](https://github.com/google/xi-editor) which uses InspiredGitHub as the default theme (you can actually see the wrong Markdown highlighting which this pull request fixes in the README screenshot). Thanks for taking your time and looking at the pull request even if you're not using Sublime Text anymore. InspiredGitHub is such an awesome theme.

**Comment by sethlopezme** [comment]
Finally got some time to take a look at this. Sorry it took a couple of days longer than I expected.

Okay, so your changes look good. There do appear to be a few more things that need to be updated. You've already pointed out the link text and image alt text colors. If I'm not mistaken, the code examples should have a gray background, as well. Looks like they currently just get a gray border or something. It's been a couple of years since I've last seen this, though, so I could be wrong. Have you made any headway on the link text and image alt colors? If not, I will go ahead and merge this and open an issue to track the other items.

Also, thanks for using my theme as the default for your front-end! I check in on the progress of Xi every now and then. It's a really interesting project.

**Comment by eyelash** [comment]
> Have you made any headway on the link text and image alt colors?

I couldn't even figure out where the violet color was coming from. There is no color like this in the Markdown section.

Edit: I figured it out: the link text used to have the scope `string.other.link.title.markdown` and then it would get its color from [this line](https://github.com/sethlopezme/InspiredGitHub.tmtheme/blob/f1692c5d3a0e8f0f7cf40126ac053602045c636b/InspiredGitHub.tmTheme#L104).

Please also consider my question above:

> maybe going for `text.html.markdown punctuation.definition` would be preferable here?

This would simplify things a lot but I'm not familiar enough with Sublime Text themes to know if it would break something.

**Comment by eyelash** [comment]
@sethlopezme I changed this pull request to use `text.html.markdown punctuation.definition`. Feel free to merge as for Sublime Text 3 it is already a big improvement.

**Comment by sethlopezme** [comment]
Just checked this out. I apologize, again, for the delay. Your update seems to work fine! Still a few other things to fix, but I'll put those in a ticket to track them. I'll merge your PR.

Thanks you for your contribution, and thanks for using my theme! I really do appreciate it.

**Pull request merged**
